FROM ubuntu:latest
RUN apt update && apt install -y curl sudo && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash && \
    sudo apt install -y nodejs && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/app
COPY . .
ENV REACT_APP_BACKEND_URL="http://localhost:8080" 
RUN npm install && \
    npm run build && \
    npm install -g serve
EXPOSE 5001
CMD ["serve", "-s", "build", "-l", "5001"]
