FROM golang:1.16.0 AS builder 
WORKDIR /usr/src/app
COPY . .
RUN go build -o server

FROM debian:stable-slim
RUN apt clean && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/server .    
ENV REQUEST_ORIGIN="http://localhost:5001"
EXPOSE 8080
CMD [ "./server" ]