FROM ubuntu:latest
RUN apt update && apt install -y curl sudo
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN sudo apt install -y nodejs
WORKDIR /usr/src/app
COPY . .
ENV REACT_APP_BACKEND_URL="http://localhost:8080" 
RUN npm install 
RUN npm run build
RUN npm install -g serve
CMD ["serve", "-s", "build", "-l", "5001"]
