FROM node:16-alpine3.18
WORKDIR /usr/src/app
COPY . .
ENV REACT_APP_BACKEND_URL="http://localhost:8080" 
RUN npm install && \
    npm install -g serve && \
    adduser -D appuser && \
    npm run build && \
    rm -rf src
USER appuser
EXPOSE 5001
CMD ["serve", "-s", "build", "-l", "5001"]
